### ISSUE TITLE
Brainstormen voor project

### ISSUE THREAD

**Issue by Rwill03** [vives-project-xp/InteractiveWall#1]
De eerste fase van het project, de benodigdheden bekijken en bespreken. Ideeën opwekken en opschrijven aan de hand van post-its en project canvas.

**Comment by LucaClrk** [comment]
We maken gebruik van het "Bare Conductive" bord. Hiermee zullen we een groot bord maken waarop we symbolen plaatsen. Deze symbolen zullen bestaan uit geleidbare verf en zullen verbonden zijn met het microcontroller adhv elektrische draden. Ook willen we een houder maken voor het bordje.
