### ISSUE TITLE
Test Setup

### ISSUE THREAD

**Issue by LucaClrk** [vives-project-xp/InteractiveWall#18]
We are testing the setup for the project. Coming into sprint 2 we have made a concept and now we are making the setup for it and testing it. We have a wooden board with nails on the backside and paint on the frontside connected with these nails. We have wrapped copper wire around these nails. When touching the conductive paint on the front connection is made with the board and the sound plays

**Comment by LucaClrk** [comment]
We are now moving from the test setup to the setup for the final project. We have the tarp we need and the wooden panel. With these components we can start working on the final setup.

**Comment by LucaClrk** [comment]
Paint has been applied and screws have been drilled. This means the setup is almost complete.

**Comment by Rwill03** [comment]
Due to the delay of the required materials, the board (concept) can't be finalised. We are missing the PowerSupply, metal roods and the reinforced copper wire. Until then, the board (concept) will be put on hold.

**Comment by LucaClrk** [comment]
We have now done the transition from the test setup to the actual setup. A new issue can be opened for this.
