### ISSUE TITLE
Marking Wooden Panel

### ISSUE THREAD

**Issue by Rwill03** [vives-project-xp/InteractiveWall#23]
Het houten bord is gearriveerd en moet "klaargemaakt" worden vooraleer de Bare Conductive geïmplementeerd kan worden.

**Comment by LucaClrk** [comment]
We are now adding the conductive paint to the board. This is taking some time and there might not be enough paint to finish the board. This conductive paint is also very expensive, so do we keep painting or find another solution?

**Comment by LucaClrk** [comment]
The panel has been painted and the screws have been drilled. Now we will let it dry untill next week when we are going to tape the tarp to the panel. Then we will test the conductivity, add the sounds and connect the bare conductive microcontroller to the backside of the panel.

**Comment by Rwill03** [comment]
We are examining the option for a "holder" for the Bare conductive microcontroller. We thought about using Iron Staffs on which the microcontroller will hang on. For the other board, other option can be considered. (such as velcro)

**Comment by LucaClrk** [comment]
The barn and rainbow still have to be marked. Not sure how we will do this as it is quite a big surface.

**Comment by LucaClrk** [comment]
All icons have been painted. We have chosen to not paint the rainbow and the barn.
