### ISSUE TITLE
Setting up prototype

### ISSUE THREAD

**Issue by LucaClrk** [vives-project-xp/InteractiveWall#29]
We are currently working on the prototype and setting it up. Changes are being made to our first plans and adapting as we go.

**Comment by LucaClrk** [comment]
We are working on a way to protect people from the nails. We are currently doing this by going over the nails with small wooden plates.

**Comment by LucaClrk** [comment]
The prototype is now almost done. We are finalizing the setup and debugging.

**Comment by Rwill03** [comment]
The board is coming together as expected. The tarp is applied.
