### ISSUE TITLE
Making a SoundBoard with ESP32

### ISSUE THREAD

**Issue by LucaClrk** [vives-project-xp/InteractiveWall#30]
We want to make the next board with the ESP32. Currently we are working on the sound board with the "Bare Conductive" board. As soon as this is done we will move on to the panel with the ESP32.

**Comment by Rwill03** [comment]
The pins are being "read" by the ESP, so touch is already working. Now we are working on integrating the sounds-player with the ESP.

**Comment by LucaClrk** [comment]
The code for the ESP32 is almost there. We have also concluded a sound set for this board. This board will be rather small because we will only have 6 capacitive sensors.

**Comment by LucaClrk** [comment]
The code for the soundboard is not working. Some work will need to be done here.

**Comment by LucaClrk** [comment]
We made a soundboard without sounds, but with LED's. We are now making the finishing touches.

**Comment by Sha88y** [comment]
finished the code to work with LED's. The board now works.
