### ISSUE TITLE
Debugging the bare conductive microcontroller

### ISSUE THREAD

**Issue by Rwill03** [vives-project-xp/InteractiveWall#32]
There is currently a "bug" that prevents the microcontroller to detect touch, this issue is of the type priority to handle. We suspect that the cause, the glue is.

**Comment by Rwill03** [comment]
As not suspected, the wiring were at fault. After a bit of arranging the cables, we got it working again.

**Comment by Rwill03** [comment]
We have noticed (after applying the tarp), that some of the pins aren't being registered. We are currently working on fixen the issue(s).

**Comment by Rwill03** [comment]
We are currently fixing the holding mechanism that holds the microcontroller in place. We are trying to improve it by using screw with bolts.

**Comment by LucaClrk** [comment]
The microcontroller has been debugged. At least we think so. The board sometimes doesn't detect the signals because the wire or screw is slightly off angle. But once working, it will keep working. But might take 5-10 minutes to get it working again after you move it.
