### ISSUE TITLE
Interactive Piano

### ISSUE THREAD

**Issue by LucaClrk** [vives-project-xp/InteractiveWall#33]
For a second board we want to make a piano. We will do this with an ESP32, a wooden board and some electric paint. We will try to recreate the sounds and looks of a piano with this board.

**Comment by Rwill03** [comment]
Now we are marking the piano tiles on the wooden board. The amount of tiles is 6.

**Comment by LucaClrk** [comment]
The piano has been painted. We also painted a button so the piano can have different sound sets. Like a synthesizer, orgal or accordion. We have painted connections from the piano to the backside of the panel. On the backside of the panel we will make the connection to the ESP32.

**Comment by Rwill03** [comment]
Now we are cutting the board to size and to remove the excess wood.

**Comment by LucaClrk** [comment]
The piano has been painted on a piece of wood. The conductive paint has been connected to the back.

**Comment by LucaClrk** [comment]
The DF Player doesn't work anymore. So we won't be making a piano with sounds. We are keeping the board with the conductive paint and will replace the df player with LED's to prove our point that this project is possible with an ESP32.

**Comment by Sha88y** [comment]
the board is complete and now works with LED's instead of sounds
