### ISSUE TITLE
Bestellijst opmaken

### ISSUE THREAD

**Issue by Rwill03** [vives-project-xp/InteractiveWall#6]
Een "voorlopige" bestellijst opmaken voor wat er nodig is voor het project.

**Comment by LucaClrk** [comment]
De nodige basis producten staan in het Excel bestand. Het kan zijn dat er door het semester hier nog een paar dingen bijkomen. Maar voor nu zijn dit de nodige producten.

**Comment by LucaClrk** [comment]
Bij verder nadenken komen er meerdere dingen bij in de bestellijst. Er zijn gedachten om een  groot zeil te plakken op een stuk hout. Dit stuk zeil moet natuurlijk eerst nog besteld worden. Dan hebben we bedacht hoe we dit zeil op een stuk hout zouden kunnen plakken. Mogelijks doen we dit met een schuimplaat tussen het hout en het zeil om het aanraken zachter te maken.
